### PR TITLE
Include the attribute today_date

### PR DESCRIPTION
**Pull request by JeffBorges**
Include the attribute today_date to set the current date of Zebra_DatePicker using the date of the server

### CODE REVIEW

**Comment by stefangabos** [comment]
There are already 2 ways of setting the current data:

- the most obious one, setting the "value" attribute of the input field
```html
<input type="text" value="2016-07-23" class="datepicker">
```

- setting the "start_date" property

**Comment by JeffBorges** [comment]
that ways setting the start date, in my case I wanted setting the current date of calendar, because I could not rely on the browser date

**Comment by stefangabos** [comment]
Server side (using PHP) that would be either
```html
<input type="text" value="<?php echo date('Y-m-d')?>" class="datepicker">
```
or
```html
<input type="text" data-zdp_start_date="<?php echo date('Y-m-d')?>" class="datepicker">
```

**Comment by JeffBorges** [comment]
with value:

image

image

with start_date:

image

image


what I need (with today_date):
image

I don't need setting the start date, I need setting the current date

**Comment by stefangabos** [comment]
No, I understand and it is something that makes sense. It's the "reference_date", and it is something that I'll implement

**Comment by JeffBorges** [comment]
Ok, Thank you.

**Pull request closed without merging**
