### PR TITLE
Implemented onViewChanged callback

### PR DESCRIPTION
**Pull request by wvankuipers**
Hello @stefangabos,

For a project we are currently working on we needed a method to update some of the datepicker settings based on the displayed month, year or year range in the detepicker's view.

To make this possible we added a new method, the `onViewChanged` method:

```
callback function to be executed when the datepicker view was changed so that the selected month, year or year range was changed

the callback function takes 4 arguments
-    string that represents the changed view (can be "days", "months" or "years")
-    object containing the current year, minimal year, maximal year and month that was selected before the view was updated
-    object containing the current year, minimal year, maximal year and month that was selected after the view was changed
-    a reference to the element that made the call for the view update

the "this" keyword inside the callback function refers to the element the date picker is attached to!
```

With this method it is possible to detect what has changed between view updates for the given datepicker.

We hope you will implement this feature to the plugin.

Regards,

Wouter

### CODE REVIEW

**Comment by ericpeeters** [comment]
:+1:

**Comment by wvankuipers** [comment]
Yes and no, the onChange event only returns the current view, the "active" elements in that view and the element the datepicker is is attached to. The problem with this is that when you only need the current displayed month, year or year range you need to loop over the active elements to "calculate" these values.

Another problem with this implementation is that is doesn't give us the previous value, so if we go back 1 month we only get the elements from the current active view (and have no clue if we went back or forward) This could also be calculated (by storing the elements in the view when the datepicker is opened and compare that with the current elements after the change) but that also turned out to be quite a hassle.

As an example we are tending to use this new callback the following way:

    function handleDateTimeViewChange(view, oldValues, newValues) {
        var $el = $(this),
            oldDate = new Date(oldValues.year, oldValues.month, 1),
            newDate = new Date(newValues.year, newValues.month, 1),
            cachedResults = $el.data('enabled_dates') || {};

        // Check if we have the enabled_dates in our cache
        if(!cachedResults[newDate.getTime()]) {
            // If not retrieve the enabled_dates from a service
            cachedResults[newDate.getTime()] = getEnabledDatesService(newDate);
            
            // Store the results in the elements data object
            $el.data('enabled_dates', cachedResults);
        }
        
        // Update the datepicker with the new enabled dates
        $el.data('Zebra_DatePicker').update({
            enabled_dates: cachedResults[newDate.getTime()]
        });
    }

    $('.js-datepicker').Zebra_DatePicker({
        onViewChanged: handleDateTimeViewChange
    });

**Comment by wvankuipers** [comment]
@stefangabos Is there any news on this? We are now on my private fork to enable this feature and having this implemented in the actual plugin would be great!

**Comment by jasondavis** [comment]
Thanks for sharing.  I don't have time but would love to see more public functions added such as these mentioned below if anyone can contribute, would appreciate it!:  

- `clearSelectedDate()`    
- `setSelectedDate('01/12/2015')`  

jQueryUI and many other Date Pickers have an easy way to set the selected date from code easily.  Zebra has an Update function however I have not been able to update selected date from code very easily.  

When the `clear date` button is visible on the Date Picker, it works great when clicked on.  There should be a way to call that from code as well!

**Pull request closed without merging**
